//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.LeaveLog = new HashSet<LeaveLog>();
            this.MonthlySalary = new HashSet<MonthlySalary>();
            this.SalaryLog = new HashSet<SalaryLog>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Title { get; set; }
        public Nullable<System.DateTime> StartWorkingDate { get; set; }
        public Nullable<System.DateTime> LeaveWorkingDate { get; set; }
        public decimal Salary { get; set; }
        public bool IsOnJob { get; set; }
        public string Memo { get; set; }
    
        public virtual ICollection<LeaveLog> LeaveLog { get; set; }
        public virtual ICollection<MonthlySalary> MonthlySalary { get; set; }
        public virtual ICollection<SalaryLog> SalaryLog { get; set; }
    }
}
