//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryLog
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public decimal BeforeSalary { get; set; }
        public decimal AfterSalary { get; set; }
        public string Reason { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
